### ISSUE TITLE
unable to validate session

### ISSUE THREAD

**Issue by aqwzs** [SchoolUtils/WebUntis#48]
how do I validate a session, I use qr-code login, it logs in perfectly but I'm unable to verify the session an thus am unable to get any other data
here's the error log:

```
(node:2476) UnhandledPromiseRejectionWarning: Error: Current Session is not valid
    at WebUntisQR._request (/home/pi/RMUntis4/node_modules/webuntis/index.js:548:71)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async WebUntisQR.getOwnTimetableForToday (/home/pi/RMUntis4/node_modules/webuntis/index.js:252:16)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2476) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2476) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by TheNoim** [comment]
Can you do some debugging? Does it fail [here](https://github.com/SchoolUtils/WebUntis/blob/b66c74df2a7b95521ff1099721eab9f007c48449/index.js#L170) or [here](https://github.com/SchoolUtils/WebUntis/blob/b66c74df2a7b95521ff1099721eab9f007c48449/index.js#L171) or [here](https://github.com/SchoolUtils/WebUntis/blob/b66c74df2a7b95521ff1099721eab9f007c48449/index.js#L187).

Sorry for the late response.

**Comment by MoDevIO** [comment]
That was also my problem... It turns out that I entered incorrect data. To ensure, that you entered the right data, use for school, username and url the info from here: webuntis -> {YOUR_NAME} -> 2nd tab and show the QR-Code. For the password, use your password, that you also use for the normal website login...
