### ISSUE TITLE
Causes for "Server didn't return any result."

### ISSUE THREAD

**Issue by DEVTomatoCake** [SchoolUtils/WebUntis#82]
I sometimes get this error and was wondering what could cause it, as webuntis itself seems to be always available.
Can I just try to repeat the request, or should I wait a few minutes before trying again?

Full error:
```js
Error: Server didn't return any result.
    at WebUntisQR._request (/home/container/node_modules/webuntis/index.js:745:42)
    at async WebUntisQR.getOwnClassTimetableForRange (/home/container/node_modules/webuntis/index.js:438:16)```

**Comment by DEVTomatoCake** [comment]
Ok I might just be bad at coding lol
Date range was out of the range the current user can see 🤷
